<script>

</script>

<template>

    <div class="header-style">

        <h1><slot></slot></h1>

        <div class="elevenlabs-container">

            Audios Generated by <a href="https://elevenlabs.io/" target="_blank" rel=external>elevenlabs.io</a>

        </div>

    </div>

</template>

<style scoped>

    .header-style {
        background-image: linear-gradient(to right, var(--cerulean700), var(--cerulean600));
        fill: var(--graycool800);
        margin-bottom: 64px;
        margin-top: 40px;
        padding-top: 40px;
        padding-bottom: 40px;

    }

    .header-style h1 {
        padding-left: 24px;
        padding-right: 24px;
        margin-left: auto;
        margin-right: auto;
        color: var(--graycool0);
        font-size: 32px;
        line-height: 40px;
    }

    @media only screen and (min-width: 600px) {
        .header-style h1 {
            max-width: 50vw;
        }
    }

    .elevenlabs-container {
        padding-left: 24px;
        padding-right: 24px;
        margin-top: 16px;
        margin-left: auto;
        margin-right: auto;
        color: var(--graycool100);
        font-weight: 100;
        font-size: 16px;
        font-style: italic;
    }

    @media only screen and (min-width: 600px) {
        .elevenlabs-container {
            max-width: 50vw;
        }
    }

    .elevenlabs-container a {
        color: var(--sunset200);
        padding: 2px;
        font-weight: 600;
        text-decoration: none;
        transition-duration: 0.2s;
    }

    .elevenlabs-container a:hover {
        color: var(--sunset300);
        transition-duration: 0.2s;
        text-decoration: underline;
    }
</style>